/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: _T90_20.c                                             *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      20                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 20                                            *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: C:\Users\LIYI\Desktop\×ÖÌå\T90²Ëµ¥ÖÐ×Ö¡ª¡ª20.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font_T90_20;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_0020[ 20] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* Start of unicode area <CJK Symbols and Punctuation> */
GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_3002[ 40] = { /* code 3002, IDEOGRAPHIC FULL STOP */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXX____,________,
  _X_X____,________,
  _XXX____,________,
  ________,________,
  ________,________,
  ________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_4F4D[ 40] = { /* code 4F4D */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___X____,X_______,
  __XX____,_X______,
  __X_XXXX,XXXXXX__,
  __X_____,________,
  _XX__X__,____X___,
  XXX__XX_,____X___,
  X_X___X_,___X____,
  __X___X_,___X____,
  __X____X,___X____,
  __X____X,__X_____,
  __X_____,__X_____,
  __X_XXXX,XXXXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_4F7F[ 40] = { /* code 4F7F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___X____,X_______,
  __XX____,X_______,
  __X_XXXX,XXXXXX__,
  __X_____,X_______,
  _XX__XXX,XXXXX___,
  XXX__X__,X___X___,
  X_X__XXX,XXXXX___,
  __X__X__,X___X___,
  __X__XX_,X_______,
  __X___XX,X_______,
  __X___XX,XXX_____,
  __X_XX__,__XXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_5173[ 40] = { /* code 5173 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___X____,__X_____,
  ____XX__,_X______,
  _____X__,X_______,
  __XXXXXX,XXXXX___,
  _______X,________,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  ______XX,________,
  ______X_,X_______,
  _____X__,_X______,
  ___XX___,__XX____,
  _XX_____,____XX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_5207[ 40] = { /* code 5207 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X_____,________,
  __X__XXX,XXXXX___,
  __X____X,___X____,
  __X_XX_X,___X____,
  XXXX___X,___X____,
  __X____X,___X____,
  __X____X,___X____,
  __X__X_X,___X____,
  __X_X__X,___X____,
  __XX__X_,___X____,
  _X___XX_,___X____,
  ____XX__,XXXX____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_53C2[ 40] = { /* code 53C2 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____XX_,X_______,
  ____X___,_XX_____,
  __XXXXXX,XXXX____,
  _____XX_,____X___,
  XXXXXXXX,XXXXXX__,
  ____X__X,XX______,
  __XX_XX_,X_XX____,
  XXXXX__X,XX__XX__,
  ____XXXX,__XX____,
  __XXX___,XXX_____,
  _____XXX,________,
  __XXX___,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_542F[ 40] = { /* code 542F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,________,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,________,
  __X_____,________,
  __X_XXXX,XXXXX___,
  __X_X___,____X___,
  _X__X___,____X___,
  _X__XXXX,XXXXX___,
  X___X___,____X___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_5B57[ 40] = { /* code 5B57 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXX___,
  _X______,____X___,
  ___XXXXX,XXX_____,
  ________,_X______,
  ________,X_______,
  XXXXXXXX,XXXXX___,
  _______X,________,
  _______X,________,
  _______X,________,
  ____XXXX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_5F00[ 40] = { /* code 5F00 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXXXX___,
  ____X___,_X______,
  ____X___,_X______,
  ____X___,_X______,
  ____X___,_X______,
  XXXXXXXX,XXXXXX__,
  ____X___,_X______,
  ____X___,_X______,
  ____X___,_X______,
  ___X____,_X______,
  __XX____,_X______,
  _XX_____,_X______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_6216[ 40] = { /* code 6216 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,X_XX____,
  ________,X___X___,
  XXXXXXXX,XXXXXX__,
  ________,X_______,
  _XXXXX__,X___X___,
  _X___X__,X__X____,
  _X___X__,X__X____,
  _XXXXX__,_XX_____,
  _X___X__,_XX__X__,
  ______X_,XXX__X__,
  XXXXXX_X,X_X__X__,
  ______XX,___XX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_62E9[ 40] = { /* code 62E9 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X__XXX,XXXXX___,
  __X___X_,___XX___,
  XXXXX__X,___X____,
  __X_____,XXX_____,
  __X____X,X_XX____,
  __XXXXX_,____XX__,
  XXX_____,_X______,
  __X___XX,XXXXX___,
  __X_____,_X______,
  __X_XXXX,XXXXXX__,
  __X_____,_X______,
  XXX_____,_X______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_6362[ 40] = { /* code 6362 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X_____,X_______,
  __X____X,XXXX____,
  XXXX_XX_,__XX____,
  __X_X___,__X_____,
  __X_XXXX,XXXXX___,
  __XX_X__,_X__X___,
  XXX__X__,_X__X___,
  __X__X__,_X__X___,
  __X_XXXX,XXXXXX__,
  __X_____,XX______,
  __X___XX,__X_____,
  XXX_XX__,___XXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_6539[ 40] = { /* code 6539 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,X_______,
  _XXXX__X,________,
  ____X__X,XXXXXX__,
  ____X_X_,___X____,
  ____X_XX,___X____,
  _XXXXX_X,___X____,
  _X__X__X,__X_____,
  _X______,X_X_____,
  _X___X__,XX______,
  _X_XX___,XXX_____,
  _XXX__XX,__XX____,
  _X__XX__,____XX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_6570[ 40] = { /* code 6570 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X__X__X,_X______,
  __X_XXX_,_X______,
  XXXXXXX_,XXXXXX__,
  ___XX___,X___X___,
  _XXXXX_X,X___X___,
  XX__X_XX,X__XX___,
  ___X____,_X_X____,
  XXXXXXX_,_X_X____,
  _X____X_,__X_____,
  __XXXX__,_XXX____,
  __XX_XXX,X__XX___,
  XX____XX,____XX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_6574[ 40] = { /* code 6574 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____X___,_X______,
  XXXXXXX_,XX______,
  _X__X_X_,XXXXXX__,
  _XXXXXXX,X___X___,
  ___XXX__,_X__X___,
  __X_X_X_,__XX____,
  XX__X__X,XX__XX__,
  _XXXXXXX,XXXXX___,
  _______X,________,
  ___X___X,XXXXX___,
  ___X___X,________,
  XXXXXXXX,XXXXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_66F4[ 40] = { /* code 66F4 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXXXX___,
  _______X,________,
  __XXXXXX,XXXX____,
  __X____X,___X____,
  __XXXXXX,XXXX____,
  __X____X,___X____,
  __X____X,___X____,
  __XXXXXX,XXXX____,
  __X____X,___X____,
  ___XX_X_,________,
  ____XXXX,________,
  XXXX____,XXXXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_7528[ 40] = { /* code 7528 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  _X_____X,____X___,
  _X_____X,_XXXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_8005[ 40] = { /* code 8005 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______X_,________,
  ______X_,____X___,
  __XXXXXX,XXXX____,
  ______X_,_XX_____,
  XXXXXXXX,XXXXXX__,
  ______XX,________,
  ___XXXXX,XXXX____,
  XXXX____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_8282[ 40] = { /* code 8282 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____X___,_X______,
  XXXXXXXX,XXXXX___,
  ____X___,_X______,
  ________,________,
  _XXXXXXX,XXXX____,
  ____X___,___X____,
  ____X___,___X____,
  ____X___,___X____,
  ____X___,___X____,
  ____X___,___X____,
  ____X__X,XXX_____,
  ____X___,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_8C03[ 40] = { /* code 8C03 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX__XXX,XXXXX___,
  __XX_X__,____X___,
  _____X__,X___X___,
  XXX__X_X,XXX_X___,
  __X__X__,X___X___,
  __X__XXX,XXXXX___,
  __X__X__,____X___,
  __X_XX_X,XXX_X___,
  __XX_X_X,__X_X___,
  _X__X__X,XXX_X___,
  ____X__X,____X___,
  ___X____,_XXXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_9009[ 40] = { /* code 9009 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X____X_,_X______,
  __X__XX_,_X______,
  ___X_XXX,XXXXX___,
  ____X___,_X______,
  XXX_____,_X______,
  __X_XXXX,XXXXXX__,
  __X____X,__X_____,
  __X____X,__X__X__,
  __X___XX,__X__X__,
  __X__XX_,__XXXX__,
  XX_X____,________,
  X___XXXX,XXXXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_95ED[ 40] = { /* code 95ED */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X__XXX,XXXXX___,
  ___X____,____X___,
  _X______,X___X___,
  _X______,X___X___,
  _X_XXXXX,XXX_X___,
  _X_____X,X___X___,
  _X____XX,X___X___,
  _X___XX_,X___X___,
  _X__XX__,X___X___,
  _X_X____,X___X___,
  _X____XX,X___X___,
  _X______,_XXXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_20_9879[ 40] = { /* code 9879 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,XXXXXX__,
  XXXXX___,X_______,
  __X_____,X_______,
  __X___XX,XXXXX___,
  __X___X_,____X___,
  __X___X_,_X__X___,
  __X___X_,_X__X___,
  __X___X_,_X__X___,
  __XXX_X_,_X__X___,
  XXX__XX_,XXX_X___,
  ______XX,___XX___,
  ____XX__,____XX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Font_T90_20_CharInfo[24] = {
   {   4,   4,  1, acGUI_Font_T90_20_0020 } /* code 0020 */
  ,{  14,  14,  2, acGUI_Font_T90_20_3002 } /* code 3002 */
  ,{  14,  14,  2, acGUI_Font_T90_20_4F4D } /* code 4F4D */
  ,{  14,  14,  2, acGUI_Font_T90_20_4F7F } /* code 4F7F */
  ,{  14,  14,  2, acGUI_Font_T90_20_5173 } /* code 5173 */
  ,{  14,  14,  2, acGUI_Font_T90_20_5207 } /* code 5207 */
  ,{  14,  14,  2, acGUI_Font_T90_20_53C2 } /* code 53C2 */
  ,{  14,  14,  2, acGUI_Font_T90_20_542F } /* code 542F */
  ,{  14,  14,  2, acGUI_Font_T90_20_5B57 } /* code 5B57 */
  ,{  14,  14,  2, acGUI_Font_T90_20_5F00 } /* code 5F00 */
  ,{  14,  14,  2, acGUI_Font_T90_20_6216 } /* code 6216 */
  ,{  14,  14,  2, acGUI_Font_T90_20_62E9 } /* code 62E9 */
  ,{  14,  14,  2, acGUI_Font_T90_20_6362 } /* code 6362 */
  ,{  14,  14,  2, acGUI_Font_T90_20_6539 } /* code 6539 */
  ,{  14,  14,  2, acGUI_Font_T90_20_6570 } /* code 6570 */
  ,{  14,  14,  2, acGUI_Font_T90_20_6574 } /* code 6574 */
  ,{  14,  14,  2, acGUI_Font_T90_20_66F4 } /* code 66F4 */
  ,{  14,  14,  2, acGUI_Font_T90_20_7528 } /* code 7528 */
  ,{  14,  14,  2, acGUI_Font_T90_20_8005 } /* code 8005 */
  ,{  14,  14,  2, acGUI_Font_T90_20_8282 } /* code 8282 */
  ,{  14,  14,  2, acGUI_Font_T90_20_8C03 } /* code 8C03 */
  ,{  14,  14,  2, acGUI_Font_T90_20_9009 } /* code 9009 */
  ,{  14,  14,  2, acGUI_Font_T90_20_95ED } /* code 95ED */
  ,{  14,  14,  2, acGUI_Font_T90_20_9879 } /* code 9879 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop24 = {
   0x9879 /* first character */
  ,0x9879 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[ 23] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop23 = {
   0x95ED /* first character */
  ,0x95ED /* last character  */
  ,&GUI_Font_T90_20_CharInfo[ 22] /* address of first character */
  ,&GUI_Font_T90_20_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop22 = {
   0x9009 /* first character */
  ,0x9009 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[ 21] /* address of first character */
  ,&GUI_Font_T90_20_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop21 = {
   0x8C03 /* first character */
  ,0x8C03 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[ 20] /* address of first character */
  ,&GUI_Font_T90_20_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop20 = {
   0x8282 /* first character */
  ,0x8282 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[ 19] /* address of first character */
  ,&GUI_Font_T90_20_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop19 = {
   0x8005 /* first character */
  ,0x8005 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[ 18] /* address of first character */
  ,&GUI_Font_T90_20_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop18 = {
   0x7528 /* first character */
  ,0x7528 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[ 17] /* address of first character */
  ,&GUI_Font_T90_20_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop17 = {
   0x66F4 /* first character */
  ,0x66F4 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[ 16] /* address of first character */
  ,&GUI_Font_T90_20_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop16 = {
   0x6574 /* first character */
  ,0x6574 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[ 15] /* address of first character */
  ,&GUI_Font_T90_20_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop15 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[ 14] /* address of first character */
  ,&GUI_Font_T90_20_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop14 = {
   0x6539 /* first character */
  ,0x6539 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[ 13] /* address of first character */
  ,&GUI_Font_T90_20_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop13 = {
   0x6362 /* first character */
  ,0x6362 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[ 12] /* address of first character */
  ,&GUI_Font_T90_20_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop12 = {
   0x62E9 /* first character */
  ,0x62E9 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[ 11] /* address of first character */
  ,&GUI_Font_T90_20_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop11 = {
   0x6216 /* first character */
  ,0x6216 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[ 10] /* address of first character */
  ,&GUI_Font_T90_20_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop10 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[  9] /* address of first character */
  ,&GUI_Font_T90_20_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop9 = {
   0x5B57 /* first character */
  ,0x5B57 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[  8] /* address of first character */
  ,&GUI_Font_T90_20_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop8 = {
   0x542F /* first character */
  ,0x542F /* last character  */
  ,&GUI_Font_T90_20_CharInfo[  7] /* address of first character */
  ,&GUI_Font_T90_20_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop7 = {
   0x53C2 /* first character */
  ,0x53C2 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[  6] /* address of first character */
  ,&GUI_Font_T90_20_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop6 = {
   0x5207 /* first character */
  ,0x5207 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[  5] /* address of first character */
  ,&GUI_Font_T90_20_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop5 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[  4] /* address of first character */
  ,&GUI_Font_T90_20_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop4 = {
   0x4F7F /* first character */
  ,0x4F7F /* last character  */
  ,&GUI_Font_T90_20_CharInfo[  3] /* address of first character */
  ,&GUI_Font_T90_20_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop3 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_Font_T90_20_CharInfo[  2] /* address of first character */
  ,&GUI_Font_T90_20_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop2 = {
   0x3002 /* first character */
  ,0x3002 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[  1] /* address of first character */
  ,&GUI_Font_T90_20_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_20_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_Font_T90_20_CharInfo[  0] /* address of first character */
  ,&GUI_Font_T90_20_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font_T90_20 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,20 /* height of font  */
  ,20 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font_T90_20_Prop1}
  ,16 /* Baseline */
  ,8 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

