/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: _T90_30B.c                                            *
* Font:        微软雅黑                                              *
* Height:      30                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 30                                            *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: C:\Users\LIYI\Desktop\字体\T90模式选择界面.txt  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font_T90_30B;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Font_T90_30B_5355[ 90] = { /* code 5355 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _____X__,________,X_______,
  _____XXX,_______X,X_______,
  ______XX,X____XXX,________,
  ___XXXXX,XXXXXXXX,XXXX____,
  ___XXXXX,XXXXXXXX,XXXX____,
  ___XX___,__XX____,__XX____,
  ___XX___,__XX____,__XX____,
  ___XXXXX,XXXXXXXX,XXXX____,
  ___XXXXX,XXXXXXXX,XXXX____,
  ___XX___,__XX____,__XX____,
  ___XX___,__XX____,__XX____,
  ___XXXXX,XXXXXXXX,XXXX____,
  ___XXXXX,XXXXXXXX,XXXX____,
  ___XX___,__XX____,__XX____,
  ________,__XX____,________,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_30B_53CC[ 90] = { /* code 53CC */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXXXXXX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXXXXXX,XXXX____,
  ________,XXXX____,__XX____,
  ________,XXXX____,__XX____,
  __X_____,X_XX____,__XX____,
  _XXX___X,X_XX____,_XX_____,
  __XX___X,X__XX___,_XX_____,
  ___XX__X,X__XX___,_XX_____,
  ___XX_XX,___XX___,_XX_____,
  ____XXXX,____XX__,XX______,
  ____XXX_,____XX__,XX______,
  _____XX_,_____XXX,XX______,
  ____XXXX,_____XXX,X_______,
  ____XXXX,X_____XX,X_______,
  ___XX__X,XX___XXX,X_______,
  __XXX___,XXX_XXX_,XX______,
  _XXX____,_X_XXX__,_XXX____,
  XXX_____,_XXXX___,__XXX___,
  _X______,XXXX____,___X____,
  ________,_X______,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_30B_5F0F[ 90] = { /* code 5F0F */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,____XX__,XX______,
  ________,____XX__,_XX_____,
  ________,____XX__,__XX____,
  ________,____XX__,__X_____,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,____XX__,________,
  ________,____XX__,________,
  ________,____XX__,________,
  _XXXXXXX,XXX_XX__,________,
  _XXXXXXX,XXX__X__,________,
  _____XX_,_____XX_,________,
  _____XX_,_____XX_,________,
  _____XX_,_____XX_,________,
  _____XX_,_____XX_,________,
  _____XX_,______XX,____XX__,
  _____XX_,XXXX__XX,____XX__,
  ___XXXXX,XXXX__XX,____XX__,
  XXXXXXXX,_______X,X__XX___,
  XXX_____,________,XXXXX___,
  ________,________,_XXX____,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_30B_62D6[ 90] = { /* code 62D6 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,_XX_____,________,
  ___XX___,_XXXXXXX,XXXXX___,
  XXXXXXX_,XXXXXXXX,XXXXX___,
  XXXXXXX_,XX______,________,
  ___XX__X,XX___XX_,________,
  ___XX___,X____XX_,_XXX____,
  ___XX___,_XX__XXX,XXXX____,
  ___XXXX_,_XXXXXXX,__XX____,
  __XXXXXX,XXXX_XX_,__XX____,
  XXXXX__X,XXX__XX_,__XX____,
  XX_XX___,_XX__XX_,__XX____,
  ___XX___,_XX__XX_,XXXX____,
  ___XX___,_XX__XX_,XXX_XX__,
  ___XX___,_XX__XX_,____XX__,
  ___XX___,_XX__XX_,____XX__,
  ___XX___,_XX_____,___XXX__,
  XXXXX___,_XXXXXXX,XXXXX___,
  XXXX____,__XXXXXX,XXXX____,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_30B_6A21[ 90] = { /* code 6A21 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XX___,__XX____,XX______,
  ___XX___,__XX____,XX______,
  ___XX__X,XXXXXXXX,XXXXX___,
  ___XX___,__XX____,XX______,
  ___XX___,__XX____,XX______,
  XXXXXXX_,________,________,
  ___XX___,XXXXXXXX,XXXX____,
  __XXX___,XX______,__XX____,
  __XXXX__,XX______,__XX____,
  __XXXXX_,XXXXXXXX,XXXX____,
  _XXXX_XX,XX______,__XX____,
  _X_XX__X,XX______,__XX____,
  XX_XX___,XXXXXXXX,XXXX____,
  XX_XX___,XX___XX_,__XX____,
  ___XX___,_____XX_,________,
  ___XX__X,XXXXXXXX,XXXXXX__,
  ___XX___,____XXXX,________,
  ___XX___,___XXX_X,X_______,
  ___XX___,_XXXX___,XXX_____,
  ___XX_XX,XXX_____,__XXXX__,
  ___XX__X,X_______,____X___,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Font_T90_30B_CharInfo[5] = {
   {  22,  22,  3, acGUI_Font_T90_30B_5355 } /* code 5355 */
  ,{  22,  22,  3, acGUI_Font_T90_30B_53CC } /* code 53CC */
  ,{  22,  22,  3, acGUI_Font_T90_30B_5F0F } /* code 5F0F */
  ,{  22,  22,  3, acGUI_Font_T90_30B_62D6 } /* code 62D6 */
  ,{  22,  22,  3, acGUI_Font_T90_30B_6A21 } /* code 6A21 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_30B_Prop5 = {
   0x6A21 /* first character */
  ,0x6A21 /* last character  */
  ,&GUI_Font_T90_30B_CharInfo[  4] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_30B_Prop4 = {
   0x62D6 /* first character */
  ,0x62D6 /* last character  */
  ,&GUI_Font_T90_30B_CharInfo[  3] /* address of first character */
  ,&GUI_Font_T90_30B_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_30B_Prop3 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_Font_T90_30B_CharInfo[  2] /* address of first character */
  ,&GUI_Font_T90_30B_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_30B_Prop2 = {
   0x53CC /* first character */
  ,0x53CC /* last character  */
  ,&GUI_Font_T90_30B_CharInfo[  1] /* address of first character */
  ,&GUI_Font_T90_30B_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_30B_Prop1 = {
   0x5355 /* first character */
  ,0x5355 /* last character  */
  ,&GUI_Font_T90_30B_CharInfo[  0] /* address of first character */
  ,&GUI_Font_T90_30B_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font_T90_30B = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,30 /* height of font  */
  ,30 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font_T90_30B_Prop1}
  ,24 /* Baseline */
  ,12 /* Height of lowercase characters */
  ,17 /* Height of capital characters */
};

