/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: _T90_30BOLD.c                                         *
* Font:        微软雅黑                                              *
* Height:      30                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 30                                            *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: C:\Users\LIYI\Desktop\字体\T90模式选择界面.txt  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font_T90_30BOLD;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Font_T90_30BOLD_5355[ 90] = { /* code 5355 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ______X_,______XX,________,
  _____XXX,______XX,XX______,
  _____XXX,X____XXX,X_______,
  ______XX,X____XXX,________,
  __XXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXXX____,
  __XXX___,__XXX___,_XXX____,
  __XXX___,__XXX___,_XXX____,
  __XXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXXX____,
  __XXX___,__XXX___,_XXX____,
  __XXX___,__XXX___,_XXX____,
  __XXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXXX____,
  ________,__XXX___,________,
  ________,__XXX___,________,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,__XXX___,________,
  ________,__XXX___,________,
  ________,__XXX___,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_30BOLD_53CC[ 90] = { /* code 53CC */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  _______X,XX______,__XXX___,
  __X____X,XX_XX___,_XXX____,
  _XXX__XX,X_XXXX__,_XXX____,
  _XXX__XX,X__XXX__,_XXX____,
  __XXX_XX,X__XXX__,_XXX____,
  __XXX_XX,X__XXX__,XXXX____,
  ___XXXXX,X___XXX_,XXX_____,
  ___XXXXX,____XXX_,XXX_____,
  ____XXXX,____XXXX,XX______,
  ____XXXX,_____XXX,XX______,
  ____XXXX,X____XXX,X_______,
  ___XXXXX,X____XXX,XX______,
  ___XXXXX,XX__XXXX,XXX_____,
  __XXXX_X,XX_XXXXX,XXXX____,
  _XXXX__X,_XXXXX__,XXXXX___,
  XXXX____,XXXXX___,_XXXXX__,
  _XX_____,_XXX____,__XXX___,
  ________,__X_____,___X____,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_30BOLD_62D6[ 90] = { /* code 62D6 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XX___,__XXX___,________,
  ___XX___,__XXX___,________,
  ___XX___,_XXXXXXX,XXXXX___,
  ___XX___,_XXXXXXX,XXXXX___,
  XXXXXXX_,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXX_____,________,
  XXXXXXXX,XX___XXX,________,
  ___XX___,XXX__XXX,__XXX___,
  ___XX___,XXX__XXX,XXXXX___,
  ___XX___,XXX_XXXX,XXXXX___,
  ___XX_XX,XXXXXXXX,__XX____,
  __XXXXXX,XXXX_XXX,__XX____,
  XXXXXXXX,XXX__XXX,__XX____,
  XXXXX___,XXX__XXX,__XX____,
  X__XX___,XXX__XXX,XXXX____,
  ___XX___,XXX__XXX,XXXX____,
  ___XX___,XXX__XXX,_XX_____,
  ___XX___,XXX__XXX,________,
  ___XX___,XXX_____,___X____,
  _XXXX___,XXX_____,___XXX__,
  _XXXX___,_XXXXXXX,XXXXX___,
  _XXXX___,__XXXXXX,XXXX____,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Font_T90_30BOLD_CharInfo[3] = {
   {  22,  22,  3, acGUI_Font_T90_30BOLD_5355 } /* code 5355 */
  ,{  22,  22,  3, acGUI_Font_T90_30BOLD_53CC } /* code 53CC */
  ,{  22,  22,  3, acGUI_Font_T90_30BOLD_62D6 } /* code 62D6 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_30BOLD_Prop3 = {
   0x62D6 /* first character */
  ,0x62D6 /* last character  */
  ,&GUI_Font_T90_30BOLD_CharInfo[  2] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_30BOLD_Prop2 = {
   0x53CC /* first character */
  ,0x53CC /* last character  */
  ,&GUI_Font_T90_30BOLD_CharInfo[  1] /* address of first character */
  ,&GUI_Font_T90_30BOLD_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_30BOLD_Prop1 = {
   0x5355 /* first character */
  ,0x5355 /* last character  */
  ,&GUI_Font_T90_30BOLD_CharInfo[  0] /* address of first character */
  ,&GUI_Font_T90_30BOLD_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font_T90_30BOLD = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,30 /* height of font  */
  ,30 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font_T90_30BOLD_Prop1}
  ,24 /* Baseline */
  ,12 /* Height of lowercase characters */
  ,17 /* Height of capital characters */
};

