/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: _T90_40.c                                             *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      40                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 40                                            *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: C:\Users\LIYI\Desktop\T90²Ëµ¥ÖÐ×Ö¡ª¡ª40.txt     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font_T90_40;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Font_T90_40_822A[160] = { /* code 822A */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ______XX,________,___X____,________,
  ______XX,________,__XXX___,________,
  _____XX_,________,___XX___,________,
  _____XX_,________,___XXX__,________,
  __XXXXXX,XXXX____,____X___,________,
  __XXXXXX,XXXX_XXX,XXXXXXXX,XXXXX___,
  __XX____,__XX_XXX,XXXXXXXX,XXXXX___,
  __XX____,__XX____,________,________,
  __XX__X_,__XX____,________,________,
  __XX_XXX,__XX____,________,________,
  __XX__XX,__XX____,________,________,
  __XX__XX,X_XX____,________,________,
  __XX___X,__XX____,XXXXXXXX,X_______,
  __XX____,__XX____,XXXXXXXX,X_______,
  __XX____,__XX____,XX_____X,X_______,
  XXXXXXXX,XXXX____,XX_____X,X_______,
  XXXXXXXX,XXXX____,XX_____X,X_______,
  __XX____,__XX____,XX_____X,X_______,
  __XX____,__XX____,XX_____X,X_______,
  __XX__X_,__XX____,XX_____X,X_______,
  __XX_XXX,__XX____,XX_____X,X_______,
  __XX__XX,__XX____,XX_____X,X___X___,
  __XX__XX,__XX____,XX_____X,X___XX__,
  __XX__XX,X_XX___X,XX_____X,X___XX__,
  __XX___X,__XX___X,X______X,X___XX__,
  _XXX____,__XX___X,X______X,X___XX__,
  _XX_____,__XX___X,X______X,X___XX__,
  _XX_____,__XX__XX,X______X,X___XX__,
  XXX_____,__XX__XX,_______X,XXXXXX__,
  XX____XX,XXXX_XXX,________,XXXXX___,
  _X____XX,XXX___X_,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font_T90_40_901F[160] = { /* code 901F */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ___X____,________,__XX____,________,
  __XXX___,________,__XX____,________,
  ___XXX__,________,__XX____,________,
  ____XXX_,_XXXXXXX,XXXXXXXX,XXXXXX__,
  ____XXX_,_XXXXXXX,XXXXXXXX,XXXXXX__,
  _____XXX,________,__XX____,________,
  ______X_,________,__XX____,________,
  ________,________,__XX____,________,
  ________,___XXXXX,XXXXXXXX,XXXX____,
  ________,___XXXXX,XXXXXXXX,XXXX____,
  _XXXXX__,___XX___,__XX____,__XX____,
  _XXXXX__,___XX___,__XX____,__XX____,
  ____XX__,___XX___,__XX____,__XX____,
  ____XX__,___XX___,__XX____,__XX____,
  ____XX__,___XXXXX,XXXXXXXX,XXXX____,
  ____XX__,___XXXXX,XXXXXXXX,XXXX____,
  ____XX__,___XX___,_XXX____,__XX____,
  ____XX__,________,XXXXXX__,________,
  ____XX__,______XX,X_XXXXXX,________,
  ____XX__,_____XXX,__XX__XX,XXX_____,
  ____XX__,___XXXX_,__XX____,XXXXX___,
  ____XX__,__XXX___,__XX____,__XXXX__,
  ____XX__,XXXX____,__XX____,____X___,
  ___XXX__,_X______,__XX____,________,
  __XXXXX_,________,__XX____,________,
  _XXX_XXX,X_______,________,________,
  XXX____X,XXXXXXXX,XXXXXXXX,XXXXXX__,
  _X______,_XXXXXXX,XXXXXXXX,XXXXX___,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Font_T90_40_CharInfo[2] = {
   {  31,  31,  4, acGUI_Font_T90_40_822A } /* code 822A */
  ,{  31,  31,  4, acGUI_Font_T90_40_901F } /* code 901F */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_40_Prop2 = {
   0x901F /* first character */
  ,0x901F /* last character  */
  ,&GUI_Font_T90_40_CharInfo[  1] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font_T90_40_Prop1 = {
   0x822A /* first character */
  ,0x822A /* last character  */
  ,&GUI_Font_T90_40_CharInfo[  0] /* address of first character */
  ,&GUI_Font_T90_40_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font_T90_40 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,40 /* height of font  */
  ,40 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font_T90_40_Prop1}
  ,32 /* Baseline */
  ,17 /* Height of lowercase characters */
  ,24 /* Height of capital characters */
};

