#ifndef _T90FONT_H
#define _T90FONT_H

#include "GUI.h"

extern GUI_CONST_STORAGE GUI_FONT GUI_Font_T90_30;
extern GUI_CONST_STORAGE GUI_FONT GUI_Font_T90_20;
extern GUI_CONST_STORAGE GUI_FONT GUI_Font_T90_24;
extern GUI_CONST_STORAGE GUI_FONT GUI_Font_T90_40;
extern GUI_CONST_STORAGE GUI_FONT GUI_Font_T90_30;
extern GUI_CONST_STORAGE GUI_FONT GUI_Font_T90_30B;
extern GUI_CONST_STORAGE GUI_FONT GUI_Font_T90_45B;
#endif



